let shopItemsData = [
    {
      id: "acgnk",
      sub_id:1,
      name: "ombre lines",
      price: 2999,
      desc: "this saree has eye-catching, multi-coloured bands with an ombre effect.",
      img: "https://www.navyasabyliva.in/media/catalog/product/cache/aa0dcfb87d57e4ea8a60f5edee050cb0/f/1/f1angmsr0015d_1.jpg",
    },
    {
      id: "mmbgu",
      sub_id:2,
      name: "ornamental bliss",
      price: 2999,
      desc: "classy and ornate! a festive collection saree which is a head turner ",
      img: "https://www.navyasabyliva.in/media/catalog/product/cache/465b2179bd9c45bc286e3fb32621b370/f/1/f1anansr0108a_1.jpg",
    },
    {
      id: "gjkllg",
      sub_id:3,
      name: "floral fantasy",
      price: 4999,
      desc: "rococo inspired print infused in the chinoiserie art. ",
      img: "https://www.navyasabyliva.in/media/catalog/product/cache/aa0dcfb87d57e4ea8a60f5edee050cb0/f/1/f1anansr0105a_1.jpg",
    },
    {
      id: "zxcvbnkl",
      sub_id:4,
      name: "song of nature",
      price: 3000,
      desc: "light in weight and displaying a breezy pattern of florals.",
      img: "https://www.navyasabyliva.in/media/catalog/product/cache/465b2179bd9c45bc286e3fb32621b370/f/1/f1anansr0107a_1.jpg",
    },
    {
    id: "BPfcmqEvCR",
      sub_id:6,
      name: "magnificent mirage",
      price: 6999,
      desc: "raise a toast to your bohemian side with these exquisite drapes endowed",
      img: "https://www.navyasabyliva.in/media/catalog/product/cache/aa0dcfb87d57e4ea8a60f5edee050cb0/f/2/f2anwfsr0212c_1.jpg",
    },
    {
      id: "qWqWtnsTFi",
      sub_id:7,
      name: "surreal waves",
      price: 3000,
      desc: "a symphony of imperial purples merging into playful pinks",
      img: "https://www.navyasabyliva.in/media/catalog/product/cache/aa0dcfb87d57e4ea8a60f5edee050cb0/f/1/f1anabsr0023c_1.jpg",
    },{
      id: "WgfHzkcA",
      sub_id:8,
      name: "South silk",
      price: 615,
      desc: "This Silk is Saree is Somewhat Heavy but look amazing on every woman.",
      img: "/type4/img4.jpg",
    },{
      id: "KHhFwOtQ",
      sub_id:9,
      name: "South silk",
      price: 715,
      desc: "This Silk is Saree is Somewhat Heavy but look amazing on every woman.",
      img: "/type4/img24.jpg",
    },{
      id: "WexRzViq",
      sub_id:10,
      name: "South silk",
      price: 815,
      desc: "This Silk is Saree is Somewhat Heavy but look amazing on every woman.",
      img: "/type4/img20.jpg",
    },{
      id: "zxcasdfghnkl",
      sub_id:11,
      name: "South silk",
      price: 690,
      desc: "This Silk is Saree is Somewhat Heavy but look amazing on every woman.",
      img: "/type4/img28.jpg",
    },{
      id: "aHUXfSbP",
      sub_id:12,
      name: "South silk",
      price: 3000,
      desc: "This Silk is Saree is Somewhat Heavy but look amazing on every woman.",
      img: "/type4/img39.jpg",
    },{
      id: "TdouwQMJ",
      sub_id:13,
      name: "South silk",
      price: 1000,
      desc: "This Silk is Saree is Somewhat Heavy but look amazing on every woman.",
      img: "/type4/img16.jpg",
    },{
      id: "tlVjRshB",
      sub_id:14,
      name: "South silk",
      price: 1200,
      desc: "This Silk is Saree is Somewhat Heavy but look amazing on every woman.",
      img: "/type4/img12.jpg",
    },{
      id: "cXTWroen",
      sub_id:15,
      name: "South silk",
      price: 999,
      desc: "This Silk is Saree is Somewhat Heavy but look amazing on every woman.",
      img: "/type4/img8.jpg",
    },{
      id: "EeUiAVFU",
      sub_id:16,
      name: "Chanderi Silk",
      price: 640,
      desc: "Chanderi Silk saree is a traditional sari made in Chanderi, Madhya Pradesh.",
      img: "/type1/img16.jpg",
    },{
      id: "lYDjnPyq",
      sub_id:17,
      name: "Chanderi Silk Blue",
      price: 740,
      desc: "Chanderi Silk saree is a traditional sari made in Chanderi, Madhya Pradesh.",
      img: "/type1/img23.jpg",
    },{
      id: "WebPILkB",
      sub_id:18,
      name: "Chanderi Silk",
      price: 640,
      desc: "Chanderi Silk saree is a traditional sari made in Chanderi, Madhya Pradesh.",
      img: "/type1/img30.jpg",
    },{
      id: "GFDSDGCD",
      sub_id:19,
      name: "Chanderi Silk",
      price: 870,
      desc: "Chanderi Silk saree is a traditional sari made in Chanderi, Madhya Pradesh.",
      img: "/type1/img37.jpg",
    },{
      id: "LXqbltEj",
      sub_id:20,
      name: "Chanderi Silk",
      price: 720,
      desc: "Chanderi Silk saree is a traditional sari made in Chanderi, Madhya Pradesh.",
      img: "/type1/img44.jpg",
    },{
      id: "rTKCsLfY",
      sub_id:21,
      name: "Chanderi Silk",
      price: 700,
      desc: "Chanderi Silk saree is a traditional sari made in Chanderi, Madhya Pradesh.",
      img: "/type1/img51.jpg",
    },{
      id: "wVvpNtOS",
      sub_id:22,
      name: "Munga Silk",
      price: 579,
      desc: "Munga Silk fabric is one of the finest and ancient silk materials in assam",
      img: "/type2/img4.jpg",
    },{
      id: "IhsJAKND",
      sub_id:23,
      name: "Munga Silk",
      price: 630,
      desc: "Munga Silk fabric is one of the finest and ancient silk materials in assam",
      img: "/type2/img8.jpg",
    },{
      id: "YABobklD",
      sub_id:24,
      name: "Munga Silk",
      price: 520,
      desc: "Munga Silk fabric is one of the finest and ancient silk materials in assam",
      img: "/type2/img12.jpg",
    },{
      id: "CpqgYQhN",
      sub_id:25,
      name: "Munga Silk",
      price: 820,
      desc: "Munga Silk fabric is one of the finest and ancient silk materials in assam",
      img: "/type2/img16.jpg",
    },{
      id: "tIaSswCC",
      sub_id:26,
      name: "Munga Silk",
      price: 570,
      desc: "Munga Silk fabric is one of the finest and ancient silk materials in assam",
      img: "/type2/img20.jpg",
    },{
      id: "llgJiXUk",
      sub_id:27,
      name: "Munga Silk",
      price: 699,
      desc: "Munga Silk fabric is one of the finest and ancient silk materials in assam",
      img: "/type2/img24.jpg",
    },{
      id: "acqJLYJv",
      sub_id:28,
      name: "Mysore silk",
      price: 660,
      desc: "Mysore silk sarees are a sight to behold. Exclusivly in karnataka",
      img: "/type3/img4.jpg",
    },{
      id: "LjLSdjcH",
      sub_id:29,
      name: "Mysore silk",
      price: 670,
      desc: "Mysore silk sarees are a sight to behold. Exclusivly in karnataka",
      img: "/type3/img8.jpg",
    },{
      id: "CNKJBgrT",
      sub_id:30,
      name: "Mysore silk",
      price: 899,
      desc: "Mysore silk sarees are a sight to behold. Exclusivly in karnataka",
      img: "/type3/img12.jpg",
    },{
      id: "uPgDiayJ",
      sub_id:31,
      name: "Mysore silk",
      price: 940,
      desc: "Mysore silk sarees are a sight to behold. Exclusivly in karnataka",
      img: "/type3/img16.jpg",
    },{
      id: "BiYrguNT",
      sub_id:32,
      name: "Mysore silk",
      price: 700,
      desc: "Mysore silk sarees are a sight to behold. Exclusivly in karnataka",
      img: "/type3/img20.jpg",
    },{
      id: "zMIlBFWv",
      sub_id:33,
      name: "Mysore silk",
      price: 693,
      desc: "Mysore silk sarees are a sight to behold. Exclusivly in karnataka",
      img: "/type3/img24.jpg",
    },{
      id: "tVZHpyDP",
      sub_id:34,
      name: "Banarasi Saree",
      price: 1499,
      desc: "The Pure Silk Banarasi Saree with attractive Rich Pallu Latest Designer",
      img: "https://cdn.shopify.com/s/files/1/0524/0238/9183/products/2f09337a-0241-439e-8a50-3a7a1564d51e_700x.jpg?v=1608786906",
    },{
      id: "SGYiQEwr",
      sub_id:35,
      name: "Kanchipuram silk",
      price: 1499,
      desc: "The Silk Kanchipuram silk saree has brocade of gold zari flower pots ",
      img: "https://cdn.shopify.com/s/files/1/0524/0238/9183/products/14248d0f-dfa7-48d9-8d0a-17e3affd5015_88fd4d1c-9952-4dc3-b21a-b3861d705546_700x.jpg?v=1608786443",
    },{
      id: "mPgCnFee",
      sub_id:36,
      name: "silk saree",
      price: 1599,
      desc: "The Silk Beautiful Dark Maroon & Golden Jacquard Work Silk Designer",
      img: "https://cdn.shopify.com/s/files/1/0524/0238/9183/products/0fc9d70f-7396-40a2-bf7d-9b6a7862582c_600x_dca5daa7-3ac9-4671-9af5-3e353de7ca83_600x.jpg?v=1626082882",
    },{
      id: "WaqsYnXG",
      sub_id:37,
      name: "Wedding Saree",
      price: 1499,
      desc: "Traditional Red Banarasi Silk Bridal Wear Saree",
      img: "https://cdn.shopify.com/s/files/1/0524/0238/9183/products/photo_2022-05-14_01-15-52_2_700x.jpg?v=1657002830",
    },{
      id: "jXrZmfS",
      sub_id:38,
      name: "Green Banarasi Saree",
      price: 3000,
      desc: "this beautiful green banarasi saree is the epitome of elegance.",
      img: "https://cdn.shopify.com/s/files/1/1760/4649/products/banarasi-saree-lawn-green-banarasi-saree-silk-saree-online-32390574964929_540x.jpg?v=1653556814",
    },{
      id: "PRdwnoJc",
      sub_id:39,
      name: "Kanjivaram Saree",
      price: 4269,
      desc: "he bridal Kanjivaram silk saree is loaded with zari work.",
      img: "https://cdn.shopify.com/s/files/1/1760/4649/products/RoshnibhatiainwinepurpleSaree_2_540x.jpg?v=1665555721",
    },{
      id: "tNvqQOsf",
      sub_id:40,
      name: "Kanjivaram Saree",
      price: 3000,
      desc: "This Winterberry Purple Kanjivaram Saree has an amazing sheen to it.",
      img: "https://cdn.shopify.com/s/files/1/1760/4649/products/kanjivaram-saree-winterberry-purple-kanjivaram-saree-silk-saree-online-30869277933761_540x.jpg?v=1665041846",
    },{
      id: "fyngJuql",
      sub_id:41,
      name: "Kanjivaram Saree",
      price: 8000,
      desc: "the saree is extremely stunning because of the golden border",
      img: "https://cdn.shopify.com/s/files/1/1760/4649/products/kanjivaram-saree-shruti-marathe-in-tawny-brown-kanjivaram-saree-silk-saree-online-31085993558209_540x.jpg?v=1648615219",
    },

  ];
  


   